server:
  port: 9001
spring:
  datasource:
    url: jdbc:h2:C:\Users\Leo\Desktop\working\tatptraining\homework\hw0415\spring-boot-employee-2020-4-14-9-19-1-295\mytestdb
  h2:
    console:
      enabled: true
